# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Offene Wahlen Österreich
author :
  name : Open Knowledge Österreich
  email: info@offenewahlen.at
  github : okfnat
  twitter : okfnat
  facebook : okfnat
description: "Offene Wahlen Österreich ist ein Community-Projekt von Open Knowledge Österreich, das sich für offene Daten und Transparenz bei Wahlen einsetzt."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://offenewahlen.at/" # the base hostname & protocol for your site
#url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
exclude:
  - "notes/"
staticurl: /assets/
disqus:
  shortname: "offene-wahlen"


# Build settings
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-watch
  - jekyll-assets
